name: .NET CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore services/CleanArchitecture/backend/src/CleanArch.sln

    - name: Build Solution
      run: dotnet build services/CleanArchitecture/backend/src/CleanArch.sln --configuration Release --no-restore